import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/services.dart';
import 'package:shared_preferences/shared_preferences.dart';

// import 'package:dts/firebase_options.dart'; // Auto-generated by Firebase CLI
import 'firebase_options.dart';

// Screens
import 'package:dts/screens/login_screen.dart';
import 'package:dts/screens/home_screen.dart';
import 'package:dts/screens/dashboard_screen.dart';
import 'package:dts/screens/vehicle_list.dart';
import 'package:dts/screens/pickup_team_list.dart';
import 'package:dts/screens/trip_list_screen.dart';
import 'package:dts/screens/expedition_screen.dart';
import 'package:dts/screens/pick_home_screen.dart';
import 'package:dts/screens/driver_home_screen.dart';
import 'package:dts/screens/accounts_home_screen.dart';
import 'package:dts/screens/crm_home_screen.dart';
import 'package:dts/screens/sales_home_screen.dart';
import 'package:dts/screens/signature_screen.dart';
import 'package:dts/screens/broadcast_screen.dart';

import 'package:dts/utils/redirect_handler.dart';

import 'constants/theme.dart';
import 'constants/common.dart';

import 'notifications/mobile_local_notification.dart';
import 'notifications/web_notification_handler_factory.dart';

/// 🔑 GLOBAL NAVIGATOR KEY
final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

/// 🌐➡️📱 CREATE THE INSTANCE HERE (THIS IS WHAT YOU ASKED)
/// This works on both Web & Mobile because of conditional imports
final webNotificationHandler = WebNotificationHandlerImpl();

RemoteMessage? initialMessage;

/// 🔙 Background FCM handler (mobile only)
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  if (kDebugMode) {
    print("📩 [Background] Message received: ${message.messageId}");
  }
}

Future<void> handleUnauthenticated() async {
  final prefs = await SharedPreferences.getInstance();
  await prefs.remove('token');

  WidgetsBinding.instance.addPostFrameCallback((_) {
    navigatorKey.currentState?.pushNamedAndRemoveUntil(
      '/login',
      (route) => false,
    );
  });

  if (navigatorKey.currentContext != null) {
    ScaffoldMessenger.of(navigatorKey.currentContext!).showSnackBar(
      const SnackBar(content: Text('Session expired. Please login again.')),
    );
  }
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  FlutterError.onError = (details) {
    FlutterError.dumpErrorToConsole(details);
  };

  // ❗ Web does NOT support background handler
  if (!kIsWeb) {
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  }
  // ADD THIS BLOCK HERE
  SystemChrome.setSystemUIOverlayStyle(
    const SystemUiOverlayStyle(
      statusBarColor: Colors.white, // Let AppBar color bleed to the top
      statusBarIconBrightness: Brightness.light, // White icons for Android
      statusBarBrightness: Brightness.dark, // White icons for iOS
    ),
  );

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});
  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  void initState() {
    super.initState();
    _initNotifications();
    _initFCMListeners();
  }

  /// ✅ ASYNC INIT (this is the fix)
  Future<void> _initNotifications() async {
    if (kIsWeb) {
      await webNotificationHandler.requestPermission();
      webNotificationHandler.listenForClicks((screen) {
        navigatorKey.currentState?.pushNamed('/$screen');
      });
    } else {
      await MobileLocalNotification.init();
    }
  }

  void _showWebForegroundMessage(RemoteMessage message) {
    final title = message.notification?.title ?? 'New Notification';
    final body = message.notification?.body ?? '';

    // Delay until UI is ready
    WidgetsBinding.instance.addPostFrameCallback((_) {
      final context = navigatorKey.currentContext;
      if (context == null) {
        if (kDebugMode) {
          print('⚠️ Context not ready, skipping SnackBar');
        }
        return;
      }

      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('$title\n$body')));
    });
  }

  void _initFCMListeners() {
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      if (kIsWeb) {
        if (kDebugMode) {
          print(
            '🌐 Web foreground message: '
            '${message.notification?.title} | ${message.notification?.body}',
          );
        }

        _showWebForegroundMessage(message);
        return;
      }

      // 📱 Mobile foreground
      MobileLocalNotification.show(message);
    });

    FirebaseMessaging.onMessageOpenedApp.listen(_handleNotificationNavigation);
  }

  void _handleNotificationNavigation(RemoteMessage message) {
    final targetScreen = message.data['screen'];
    if (targetScreen != null) {
      navigatorKey.currentState?.pushNamed('/$targetScreen');
    }
  }

  @override
  Widget build(BuildContext context) {
    // Define your desired tablet width
    final double tabletWidth = 768.0; // Common tablet portrait width

    return MaterialApp(
      title: appName,
      theme: appTheme,
      debugShowCheckedModeBanner: false,
      navigatorKey: navigatorKey,
      // Use the builder property to wrap all content rendered by MaterialApp
      builder: (context, child) {
        if (kIsWeb) {
          // If it's a web app, wrap the child (which is your entire app content)
          // in a Center and SizedBox to force tablet width.
          return Center(
            child: SizedBox(
              width: tabletWidth,
              child: child, // The child here is the actual content of your app
            ),
          );
        } else {
          // For non-web platforms (mobile, desktop app), return the child as is
          return child!;
        }
      },
      // Your existing routes remain the same
      home: const RedirectHandler(),
      routes: {
        '/login': (context) => const LoginScreen(),
        '/home': (context) => const HomeScreen(),
        '/dashboard_screen': (context) => const DashboardScreen(),
        '/vehicle_list': (context) => const VehicleList(),
        '/pickup_team': (context) => const PickupTeamList(),
        '/trip_list_screen': (context) => const TripListScreen(),
        '/expedition_screen': (context) => const ExpeditionScreen(),
        '/pick_home_screen': (context) => const PickHomeScreen(),
        '/driver_home_screen': (context) => const DriverHomeScreen(),
        '/accounts_home_screen': (context) => const AccountsHomeScreen(),
        '/crm_home_screen': (context) => const CrmHomeScreen(),
        '/sales_home_screen': (context) => const SalesHomeScreen(),
        '/signature_screen': (context) => const SignatureScreen(),
        '/broadcast_screen': (context) => const BroadCastScreen(),
      },
    );
  }
}
//end of main.dart